### PR TITLE
[r3]Add the 1.0 biomes, tweak certain snippets to be more readable.

### PR DESCRIPTION
**Pull request by tyrope**
There are 1 minor issues with this version:

[Kerbin's "Location Biomes" shouldn't be listed at altitude](https://github.com/tyrope/ksp-science-checklist/issues/1)
[PDF pagebreaks are incorrect](https://github.com/tyrope/ksp-science-checklist/issues/2)

### CODE REVIEW

**Comment by tyrope** [comment]
I have a new OUT.html locally, but since I do not know what exactly the OUT-tweaked version has tweaked, I'll not update that yet.

**Comment by tkbletsc** [comment]
OUT-tweaked changed a lot...I basically used the script to get in the ballpark, then edited manually to get something presentable.  I really appreciate you trying to clean up and update this...thanks!

**Comment by tyrope** [comment]
If it turns out the Location Biomes are too much of a hassle to deal with, I made a noLocationBiomes branch on my fork that removes these... at least until we can get it properly parsed.

I noticed on your site you mentioned a lot of line numbers, naturally these have now all been changed. Could you put the points you mentioned on your site into the code as comments? Keeps all the information together and might encourage others to help.

**Comment by tkbletsc** [comment]
Sorry, I was on my way out of work when I wrote that, and I don't have 
git installed there.  I've just committed an update that adds those 
comments.
- Tyler

**Pull request merged**
